### ISSUE TITLE
运行此项目崩溃

### ISSUE THREAD

**Issue by JasonYinH** [SheTieJun/wangEditor-Android#1]
Process: com.wangeditor.android, PID: 19256
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.reflect.InvocationTargetException
        at android.app.ActivityThread.installProvider(ActivityThread.java:8186)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7722)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7586)
        at android.app.ActivityThread.access$2600(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)

**Comment by SheTieJun** [comment]
你这个提供的信息太少，看错误是 startup这个库没有加载成功，你可以尝试clean 后rebuild
